// Code generated by protoc-gen-go.
// source: proto3/proto3.proto
// DO NOT EDIT!

/*
Package three is a generated protocol buffer package.

It is generated from these files:
	proto3/proto3.proto

It has these top-level messages:
	TestMessageWrapper
*/
package three

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import two "proto2"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestMessageWrapper struct {
	TestMessageWrapper *two.TestMessage `protobuf:"bytes,1,opt,name=test_message_wrapper,json=testMessageWrapper" json:"test_message_wrapper,omitempty"`
}

func (m *TestMessageWrapper) Reset()                    { *m = TestMessageWrapper{} }
func (m *TestMessageWrapper) String() string            { return proto.CompactTextString(m) }
func (*TestMessageWrapper) ProtoMessage()               {}
func (*TestMessageWrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestMessageWrapper) GetTestMessageWrapper() *two.TestMessage {
	if m != nil {
		return m.TestMessageWrapper
	}
	return nil
}

func init() {
	proto.RegisterType((*TestMessageWrapper)(nil), "three.TestMessageWrapper")
}

func init() { proto.RegisterFile("proto3/proto3.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x37, 0xd6, 0x87, 0x50, 0x7a, 0x60, 0x4a, 0x88, 0xb5, 0x24, 0xa3, 0x28, 0x35, 0x55, 0x0a,
	0x22, 0x67, 0x04, 0x91, 0x33, 0x82, 0xc8, 0x29, 0x45, 0x70, 0x09, 0x85, 0xa4, 0x16, 0x97, 0xf8,
	0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x86, 0x17, 0x25, 0x16, 0x14, 0xa4, 0x16, 0x09, 0x39, 0x71,
	0x89, 0x94, 0xa4, 0x16, 0x97, 0xc4, 0xe7, 0x42, 0x84, 0xe3, 0xcb, 0x21, 0xe2, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0xdc, 0x46, 0x02, 0x7a, 0x25, 0xe5, 0xf9, 0x7a, 0x48, 0xda, 0x82, 0x84, 0x4a, 0x30,
	0xcc, 0x48, 0x62, 0x83, 0xb8, 0x01, 0x10, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x5f, 0xeb, 0x9f, 0x93,
	0x00, 0x00, 0x00,
}
